((---
title: "Analysis for Table 1"
author: "Aaron R. Caldwell"
date: "2/25/2021"
output: word_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,message=FALSE,warning=FALSE)
source('Table1_analysis.R')
```

# Tc Max
```{r}
knitr::kable(anova_tcmax,
             caption = "ANOVA")
```
```{r}
knitr::kable(gh_tcmax %>%
               select(-.y.),
             caption = "Pairwise Comparisons",
             digits = 3)
```
```{r}
plot_tcmax
```
\newpage

# Time to Tcmax (Heating Time) 
```{r}
knitr::kable(anova_heat_time,
             caption = "ANOVA")
```
```{r}
knitr::kable(gh_heat_time %>%
               select(-.y.),
             caption = "Pairwise Comparisons")
```
```{r}
plot_heat_time
```

\newpage

# Thermal Load

```{r}
knitr::kable(anova_thermal_load,
             caption = "ANOVA")
```
```{r}
knitr::kable(gh_thermal_load %>%
               select(-.y.),
             caption = "Pairwise Comparisons")
```
```{r}
plot_thermal_load
```

\newpage

# Running Time

```{r}
knitr::kable(anova_run_time,
             caption = "ANOVA")
```
```{r}
knitr::kable(gh_run_time %>%
               select(-.y.),
             caption = "Pairwise Comparisons")
```
```{r}
plot_run_time
```

\newpage

# Distance Run

```{r}
knitr::kable(anova_dist_ran,
             caption = "ANOVA")
```
```{r}
knitr::kable(gh_dist_ran %>%
               select(-.y.),
             caption = "Pairwise Comparisons")
```
```{r}
plot_dist_ran
```

\newpage

# Dehydration (%)

```{r}
knitr::kable(anova_dehyd,
             caption = "ANOVA")
```
```{r}
knitr::kable(gh_dehyd %>%
               select(-.y.),
             caption = "Pairwise Comparisons")
```
```{r}
plot_dehyd
```

\newpage

# Hypothermic Depth (Tcmin)

```{r}
knitr::kable(anova_tcmin,
             caption = "ANOVA")
```
```{r}
knitr::kable(gh_tcmin %>%
               select(-.y.),
             caption = "Pairwise Comparisons")
```
```{r}
plot_tcmin
```

\newpage

# Duration of Hypothermia

```{r}
knitr::kable(anova_duration,
             caption = "ANOVA")
```
```{r}
knitr::kable(gh_duration %>%
               select(-.y.),
             caption = "Pairwise Comparisons")
```
```{r}
plot_duration
```
